name: "server_srv"
mode: "dev"
ip: "127.0.0.1"
rpcPort: 8010
httpPort: 8011
version: "v0.0.1"

log:
  level: "debug"
  filename: "server_srv.log"
  max_size: 200
  max_age: 30
  max_backups: 7

mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "123456"
  dbname: "acquisition"
  max_open_conns: 100
  max_idle_conns: 10

redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100