// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.0
// source: server.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	Server_UploadMetric_FullMethodName = "/proto.Server/UploadMetric"
	Server_QueryMetric_FullMethodName  = "/proto.Server/QueryMetric"
	Server_UploadLog_FullMethodName    = "/proto.Server/UploadLog"
	Server_QueryLog_FullMethodName     = "/proto.Server/QueryLog"
)

// ServerClient is the client API for Server service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ServerClient interface {
	UploadMetric(ctx context.Context, in *UploadMetricReq, opts ...grpc.CallOption) (*UploadMetricResp, error)
	QueryMetric(ctx context.Context, in *QueryMetricReq, opts ...grpc.CallOption) (*QueryMetricResp, error)
	UploadLog(ctx context.Context, in *UploadLogReq, opts ...grpc.CallOption) (*UploadLogResp, error)
	QueryLog(ctx context.Context, in *QueryLogReq, opts ...grpc.CallOption) (*QueryLogResp, error)
}

type serverClient struct {
	cc grpc.ClientConnInterface
}

func NewServerClient(cc grpc.ClientConnInterface) ServerClient {
	return &serverClient{cc}
}

func (c *serverClient) UploadMetric(ctx context.Context, in *UploadMetricReq, opts ...grpc.CallOption) (*UploadMetricResp, error) {
	out := new(UploadMetricResp)
	err := c.cc.Invoke(ctx, Server_UploadMetric_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) QueryMetric(ctx context.Context, in *QueryMetricReq, opts ...grpc.CallOption) (*QueryMetricResp, error) {
	out := new(QueryMetricResp)
	err := c.cc.Invoke(ctx, Server_QueryMetric_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) UploadLog(ctx context.Context, in *UploadLogReq, opts ...grpc.CallOption) (*UploadLogResp, error) {
	out := new(UploadLogResp)
	err := c.cc.Invoke(ctx, Server_UploadLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *serverClient) QueryLog(ctx context.Context, in *QueryLogReq, opts ...grpc.CallOption) (*QueryLogResp, error) {
	out := new(QueryLogResp)
	err := c.cc.Invoke(ctx, Server_QueryLog_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ServerServer is the server API for Server service.
// All implementations must embed UnimplementedServerServer
// for forward compatibility
type ServerServer interface {
	UploadMetric(context.Context, *UploadMetricReq) (*UploadMetricResp, error)
	QueryMetric(context.Context, *QueryMetricReq) (*QueryMetricResp, error)
	UploadLog(context.Context, *UploadLogReq) (*UploadLogResp, error)
	QueryLog(context.Context, *QueryLogReq) (*QueryLogResp, error)
	mustEmbedUnimplementedServerServer()
}

// UnimplementedServerServer must be embedded to have forward compatible implementations.
type UnimplementedServerServer struct {
}

func (UnimplementedServerServer) UploadMetric(context.Context, *UploadMetricReq) (*UploadMetricResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadMetric not implemented")
}
func (UnimplementedServerServer) QueryMetric(context.Context, *QueryMetricReq) (*QueryMetricResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMetric not implemented")
}
func (UnimplementedServerServer) UploadLog(context.Context, *UploadLogReq) (*UploadLogResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadLog not implemented")
}
func (UnimplementedServerServer) QueryLog(context.Context, *QueryLogReq) (*QueryLogResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryLog not implemented")
}
func (UnimplementedServerServer) mustEmbedUnimplementedServerServer() {}

// UnsafeServerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ServerServer will
// result in compilation errors.
type UnsafeServerServer interface {
	mustEmbedUnimplementedServerServer()
}

func RegisterServerServer(s grpc.ServiceRegistrar, srv ServerServer) {
	s.RegisterService(&Server_ServiceDesc, srv)
}

func _Server_UploadMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadMetricReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).UploadMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_UploadMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).UploadMetric(ctx, req.(*UploadMetricReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_QueryMetric_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMetricReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).QueryMetric(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_QueryMetric_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).QueryMetric(ctx, req.(*QueryMetricReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_UploadLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).UploadLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_UploadLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).UploadLog(ctx, req.(*UploadLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Server_QueryLog_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryLogReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ServerServer).QueryLog(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Server_QueryLog_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ServerServer).QueryLog(ctx, req.(*QueryLogReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Server_ServiceDesc is the grpc.ServiceDesc for Server service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Server_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.Server",
	HandlerType: (*ServerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UploadMetric",
			Handler:    _Server_UploadMetric_Handler,
		},
		{
			MethodName: "QueryMetric",
			Handler:    _Server_QueryMetric_Handler,
		},
		{
			MethodName: "UploadLog",
			Handler:    _Server_UploadLog_Handler,
		},
		{
			MethodName: "QueryLog",
			Handler:    _Server_QueryLog_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "server.proto",
}
